[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "spatialim"
version = "2.0.0"
description = "Spatial seismic intensity simulation library"
readme = "README.md"
authors = [{name = "Tian You", email = "youtian@njtech.edu.cn"}]
license = "GPL-3.0-or-later"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
keywords = ["earthquake", "seismic", "simulation", "spatial", "intensity"]
dependencies = [
    "matplotlib",
    "scipy", 
    "pandas"
]

[project.urls]
Homepage = "https://github.com/youtian95/spatialim"
Documentation = "https://github.com/youtian95/spatialim/blob/rust/README.md"
Repository = "https://github.com/youtian95/spatialim.git"
Changelog = "https://github.com/youtian95/spatialim/blob/rust/CHANGELOG.md"


[tool.maturin]
python-source = "python"
module-name = "spatialim._spatialim"
exclude = ["**/*.pyd", "**/*.so", "**/*.dylib"]

